# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rpackage.proto\x12\x08packages\"5\n\x0epackageRequest\x12\x12\n\nclient_key\x18\x01 \x01(\t\x12\x0f\n\x07type_ai\x18\x02 \x01(\t\"n\n\x13PackageExistRequest\x12\x12\n\nclient_key\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0cis_superuser\x18\x03 \x01(\t\x12\x10\n\x08is_staff\x18\x04 \x01(\t\x12\x0f\n\x07type_ai\x18\x05 \x01(\t\"\x1a\n\x0cPackageReply\x12\n\n\x02id\x18\x01 \x03(\x05\"%\n\x11PackageExistReply\x12\x10\n\x08is_exist\x18\x01 \x01(\t2\x9a\x01\n\x07Package\x12\x41\n\x0bListPackage\x12\x18.packages.packageRequest\x1a\x16.packages.PackageReply\"\x00\x12L\n\x0c\x45xistPackage\x12\x1d.packages.PackageExistRequest\x1a\x1b.packages.PackageExistReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_PACKAGEREQUEST']._serialized_start = 27
    _globals['_PACKAGEREQUEST']._serialized_end = 80
    _globals['_PACKAGEEXISTREQUEST']._serialized_start = 82
    _globals['_PACKAGEEXISTREQUEST']._serialized_end = 192
    _globals['_PACKAGEREPLY']._serialized_start = 194
    _globals['_PACKAGEREPLY']._serialized_end = 220
    _globals['_PACKAGEEXISTREPLY']._serialized_start = 222
    _globals['_PACKAGEEXISTREPLY']._serialized_end = 259
    _globals['_PACKAGE']._serialized_start = 262
    _globals['_PACKAGE']._serialized_end = 416
# @@protoc_insertion_point(module_scope)
