# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_pb2 as user__pb2


class UserStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserAuth = channel.unary_unary(
                '/users.User/UserAuth',
                request_serializer=user__pb2.userRequest.SerializeToString,
                response_deserializer=user__pb2.userReply.FromString,
                )


class UserServicer(object):
    """The greeting service definition.
    """

    def UserAuth(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.UserAuth,
                    request_deserializer=user__pb2.userRequest.FromString,
                    response_serializer=user__pb2.userReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """The greeting service definition.
    """

    @staticmethod
    def UserAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.User/UserAuth',
            user__pb2.userRequest.SerializeToString,
            user__pb2.userReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
