# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x05users\"!\n\x0buserRequest\x12\x12\n\nclient_key\x18\x01 \x01(\t\"k\n\tuserReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cis_superuser\x18\x03 \x01(\t\x12\x10\n\x08is_staff\x18\x04 \x01(\t\x12\x17\n\x0fpermission_list\x18\x05 \x03(\t28\n\x04User\x12\x30\n\x08UserAuth\x12\x12.users.userRequest\x1a\x10.users.userReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=21
  _globals['_USERREQUEST']._serialized_end=54
  _globals['_USERREPLY']._serialized_start=56
  _globals['_USERREPLY']._serialized_end=163
  _globals['_USER']._serialized_start=165
  _globals['_USER']._serialized_end=221
# @@protoc_insertion_point(module_scope)
