# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: part.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npart.proto\x12\x05parts\x1a\x1bgoogle/protobuf/empty.proto\"!\n\x0bpartRequest\x12\x12\n\nclient_key\x18\x01 \x01(\t\"6\n\tpartReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"2\n\rPartListReply\x12!\n\x07results\x18\x01 \x03(\x0b\x32\x10.parts.partReply2:\n\x04Part\x12\x32\n\x04List\x12\x12.parts.partRequest\x1a\x14.parts.PartListReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'part_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PARTREQUEST']._serialized_start=50
  _globals['_PARTREQUEST']._serialized_end=83
  _globals['_PARTREPLY']._serialized_start=85
  _globals['_PARTREPLY']._serialized_end=139
  _globals['_PARTLISTREPLY']._serialized_start=141
  _globals['_PARTLISTREPLY']._serialized_end=191
  _globals['_PART']._serialized_start=193
  _globals['_PART']._serialized_end=251
# @@protoc_insertion_point(module_scope)
